### ISSUE TITLE
Creating clients with SSP 1.18

### ISSUE THREAD

**Issue by restena-sw** [sgomez/simplesamlphp-module-oauth2#15]
Hello,

I successfully installed and configured the module and DBAL.

My deployment by default uses the new Twig UI.

Issue 1: the "Create client" link is not displayed when using the new admin module in Twig. It is shown when disabling new UI.

Issue 2: on old UI, upon clicking the Create client link, an error is thrown:

Caused by: Exception: Template: Could not find template file [oauth2:registry_list] at [/...baseurl/modules/oauth2/templates/registry_list]
Backtrace:
4 lib/SimpleSAML/XHTML/Template.php:639 (SimpleSAML\XHTML\Template::findTemplatePath)
3 lib/SimpleSAML/XHTML/Template.php:545 (SimpleSAML\XHTML\Template::show)
2 modules/oauth2/www/registry.php:39 (require)
1 lib/SimpleSAML/Module.php:254 (SimpleSAML\Module::process)

Looking at this templates directory, I find exclusively .twig files:

$ ls
registry_edit.twig  registry_list.twig  registry_new.twig

But twig templates only come into play when using new UI. In which I don't get to click the link that takes me there...

What am I missing here?

**Comment by sgomez** [comment]
Hi,

This module is not under maintenance. It was replaced by this one:

https://github.com/rediris-es/simplesamlphp-module-oidc

It supports OAuth2 and OIDC.

Anyway, this issue with newui happens too with the oidc module, because a BC with Twig template. It is resolved in master branch and I hope to release a new version next week. I need to do some more tests.

Sorry for the inconvenience.
